---
# tasks file for roles/aws
#
- name: "Fail when a mandatory extra vars are not defined"
  fail:
    msg: "AWS neccesary variable is not included"
  when:
    - project is not defined
    - action is not defined
    - instance is not defined

- name: "Show the selected action"
  debug:
    msg:
      - "Action: {{ action }}"
      - "Project: {{ project }}"
      - "Instance: {{ instance }}"

- name: "Add AWS instance"
  include_tasks: add-instance.yml
  when: action == "add"

- name: "Start AWS instance"
  include_tasks: start-instance.yml
  when: action == "start"

- name: "Stop AWS instance"
  include_tasks: stop-instance.yml
  when: action == "stop"

- name: "Delete AWX instance"
  include_tasks: delete-instance.yml
  when: action == "delete"

- name: "Add Public IP Inventory"
  include_tasks: add-public-ip-inventory.yml
  when: action == "add-public-ip-inventory"
...
